DROP TABLE IF EXISTS audit_events CASCADE;
DROP TABLE IF EXISTS outbox_events CASCADE;
DROP TABLE IF EXISTS business_identifiers CASCADE;
DROP TABLE IF EXISTS job_business_records CASCADE;
DROP TABLE IF EXISTS business_entities CASCADE;
DROP TABLE IF EXISTS crawl_pages CASCADE;
DROP TABLE IF EXISTS crawl_jobs CASCADE;
